### ISSUE TITLE
Provide pass-through for npm audit options such as --production

### ISSUE THREAD

**Issue by joebowbeer** [naugtur/npm-audit-resolver#18]
Recent versions of npm audit can ignore devDependencies using the `--production` flag.

I'd like check-audit to be at least as capable as npm audit. A simple list of pass-through options may suffice.

Regarding yarn support for devDependencies in particular, it looks like they are not checked consistently: https://github.com/yarnpkg/yarn/issues/7047

**Comment by naugtur** [comment]
I'm considering ignoring dev dependencies by default...

Incomplete yarn support makes this issue lean towards just having a way to pass flags down

**Comment by naugtur** [comment]
@joebowbeer @pdusen Thanks for your contributions!
