### ISSUE TITLE
yarn --groups passthrough doesn't work with multiple groups

### ISSUE THREAD

**Issue by Undistraction** [naugtur/npm-audit-resolver#28]
Yarn supports a `--groups` flag for audit, allowing multiple groups to be passed in:
```
yarn --groups dependencies peerDependencies optionalDependencies
```
However the following:
```
resolve-audit --yarn --groups dependencies peerDependencies optionalDependencies
```
Appears to result in a re-ordering of the flags. This is audit-resolver's output:
```
>>>> yarn audit --json peerDependencies optionalDependencies --groups dependencies
```

**Comment by naugtur** [comment]
That might be a feature of the yargs parser. I knew pass-through is gonna cause trouble. 

Sorry I took so long to notice this. Did you solve it by any chance?

**Comment by Undistraction** [comment]
@naugtur fwiw this is still broken.

**Comment by naugtur** [comment]
Are you sure it's not just random? It depends on the order of arguments which is not guaranteed.

Also, if you're passing '--something argument' there should be no spaces in the argument or argument needs to be quoted. The convention is to repeat the --something for each argument in CMD utils I know of. So this example was a little odd to begin with.
