### ISSUE TITLE
Suggestion - check-audit argument to ignore dev dependencies?

### ISSUE THREAD

**Issue by snappyfoo** [naugtur/npm-audit-resolver#32]
What is the feasibility / likelihood of this feature?
Use case: never wanting audit problems with dev dependencies to cause CI issues. Review of dev dependency issues can be done manually at regular intervals.

**Comment by naugtur** [comment]
It's already there. --production is passed to npm command underneath. 
Actually, all switches that this app doesn't consume are passed down

**Comment by snappyfoo** [comment]
Thanks @naugtur, I'll try it out. I didn't spot any documentation for it.
