### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by mfrieling** [naugtur/npm-audit-resolver#38]
I just installed `npm-audit-resolver` as described and executed `resolve-audit` and immediately got this error message:

```
>>>> npm audit --json
>>>> exit: 0
TypeError: Cannot read property 'reduce' of undefined
    at Object.askForResolutions (/home/linuxbrew/.linuxbrew/lib/node_modules/npm-audit-resolver/src/resolve/auditResolver.js:13:50)
    at /home/linuxbrew/.linuxbrew/lib/node_modules/npm-audit-resolver/resolve.js:17:30
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

My intention of using this tool is to fix all dependencies listed by `npm audit` except one, which triggers a deprecation warning about several dozen times. As this deprecation is located in an external (commercial) package which I can't fix I want to keep Sass version < 1.32.0 until the vendor provides a fix.

**Comment by lenymo** [comment]
I have just noticed a similar thing when I tried to run `resolve-audit` today on my Mac running Big Sur 11.3.1.

Here's my error:

```
>>>> npm audit --json 
>>>> exit: 0
TypeError: Cannot read property 'reduce' of undefined
    at Object.askForResolutions (/usr/local/lib/node_modules/npm-audit-resolver/src/resolve/auditResolver.js:13:50)
    at /usr/local/lib/node_modules/npm-audit-resolver/resolve.js:17:30
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by mkatanski** [comment]
I'm afraid I have the same issue. 

> System:
> MacOS Catalina 10.15.7
> Node.js v14.15.0
> npm-audit-resolver 2.3.0

error:

```bash
>>>> npm audit --json --registry https://registry.npmjs.org
>>>> exit: 0
TypeError: Cannot read property 'reduce' of undefined
    at Object.askForResolutions (/node_modules/npm-audit-resolver/src/resolve/auditResolver.js:13:50)
    at node_modules/npm-audit-resolver/resolve.js:17:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by naugtur** [comment]
Hi, thanks for reporting. It's a duplicate.
https://github.com/naugtur/npm-audit-resolver/issues/34

npm version 7 has introduced a significant breaking change to the audit output and I'm only now figuring it out. 

For now, a workaround is to use npm6 or yarn1 audit capabilities or installing npm6 as a dev dependency if that's more suitable.

**Comment by naugtur** [comment]
closing in favor of #34
