### ISSUE TITLE
Windows cmd directory prompt disappears after running

### ISSUE THREAD

**Issue by DavidJFowler** [naugtur/npm-audit-resolver#41]
If I run `check-audit` in a Windows command prompt, the directory path prompt disappears.

Windows 10
npm 7.14.0
npm-audit-resolver 3.0.0-0 (next)

See below, after the check-audit completes execution, there is no `D:\source\repos\better-npm-audit-demo>` prompt visible. The caret is still displayed and I can still run commands as shown by the output from `dir`

```
D:\source\repos\better-npm-audit-demo>check-audit
>>>> npm audit --json
>>>> npm ls --depth=0 --json
Total of 3 actions to process
audit ok.
dir
 Volume in drive D is DATA DRIVE
 Volume Serial Number is A09D-822C

 Directory of D:\source\repos\better-npm-audit-demo

02/06/2021  10:51    <DIR>          .
```

**Comment by naugtur** [comment]
Interesting...
This may be an issue with the chalk package.
Are you saying it didn't happen with V2 only V3?

**Comment by DavidJFowler** [comment]
> Are you saying it didn't happen with V2 only V3?

Just tried with v2. It still occurs.

**Comment by naugtur** [comment]
Does it recover when you hit "enter" or stay without a prompt forever?
Maybe it's something to do with the stdout handling...

**Comment by DavidJFowler** [comment]
> Does it recover when you hit "enter" or stay without a prompt forever?

Stays without a prompt forever. If I enter `cmd` I get a prompt, but if I then enter `exit` it goes back to no prompt.

**Comment by naugtur** [comment]
Can you check if 'env' differs before a d after running it?

**Comment by DavidJFowler** [comment]
No change

```
D:\source\repos\better-npm-audit-demo>set > env.txt

D:\source\repos\better-npm-audit-demo>check-audit
>>>> npm audit --json
>>>> npm ls --depth=0 --json
Total of 3 actions to process
audit ok.
set > env2.txt
fc env.txt env2.txt
Comparing files env.txt and ENV2.TXT
FC: no differences encountered
```

**Comment by naugtur** [comment]
Ok, I ran out of immediate ideas. 
I don't have access to a windows machine. 

Try going into the src/views/package.js and removing the emoji on line 42. That's the last thing to try without more research

**Comment by DavidJFowler** [comment]
I don't think it's your package.

`npm --version` destroys the prompt for me

```
D:\source\repos\npm-audit-resolver>npm --version
6.14.13

npm --version
6.14.13
```

Thanks for your help.
