### ISSUE TITLE
Any plan to support yarn?

### ISSUE THREAD

**Issue by nulltoken** [naugtur/npm-audit-resolver#5]
Would supporting `yarn --audit` be a suitable feature?

**Comment by naugtur** [comment]
Didn't know yarn exposes audit.

The goal of this package is to eventually become a part of npm cli, so I'm not sure where to fit yarn support.

Anyway, I'm working with npm to figure out the functionality and that's where my focus is for now. But I'm open to keeping it reusable if feature parity is feasible.

You want to help or just asking? ;)

**Comment by nulltoken** [comment]
>Didn't know yarn exposes audit.

see https://yarnpkg.com/lang/en/docs/cli/audit/

>But I'm open to keeping it reusable if feature parity is feasible.
>You want to help or just asking? ;)

Provided you think this package could (and should) actually work with both package managers, I'd very very open to help making that happen.

**Comment by naugtur** [comment]
Happy to hear you're willing to help.
I hope you're also willing to wait, as the RFC process in npm is moving slowly and it'll likely take a few more months to figure out what this should do. Then it's a matter of writing the right adapters - that's where we collaborate :)

Check out the RFC and if you want to use the current version with yarn, you'd need to replace the call to npm audit --json with a yarn command returning the same. 
Let me know if you try it

**Comment by nulltoken** [comment]
> Check out the RFC

Found it at https://github.com/npm/rfcs/pull/18

>if you want to use the current version with yarn, you'd need to replace the call to npm audit --json with a yarn command returning the same.

Thanks a lot, I'm going to take a look.

**Comment by naugtur** [comment]
#8 is now a possibility.

**Comment by nulltoken** [comment]
@naugtur Thanks for that. Subscribed.

Closing this.
