### ISSUE TITLE
3.0.0-6 release

### ISSUE THREAD

**Issue by FBNitro** [naugtur/npm-audit-resolver#55]
Hi, I'm just checking, was the 3.0.0-6 release intentionally marked as the latest release? 

I noticed it showed up, and when I look here, I don't see any information or even a tag for the release.

**Comment by naugtur** [comment]
Oh. No, that was not yet supposed to be latest. I'll clean it up btw of releasing 3.0.0-7

**Comment by naugtur** [comment]
fixed
