### ISSUE TITLE
support audit-level when running check-audit?

### ISSUE THREAD

**Issue by ptc-tyourchuck** [naugtur/npm-audit-resolver#65]
Can `check-audit` behave similar to `npm audit` when given an `audit-level` arg? i.e. non-zero exit code only if there are un-ignored issues left at that level or above ?

https://docs.npmjs.com/cli/v9/commands/npm-audit#audit-level

**Comment by naugtur** [comment]
AFAIR it was implemented. Make sure you're testing v3x not v2 - `npm install npm-audit-resolver@next`

**Comment by joebowbeer** [comment]
Dup of #22 ?

**Comment by ptc-tyourchuck** [comment]
great! Thanks, replied in https://github.com/naugtur/npm-audit-resolver/issues/22#issuecomment-1450622391
