### ISSUE TITLE
Ability to produce JSON output file?

### ISSUE THREAD

**Issue by MarkSkillen** [naugtur/npm-audit-resolver#7]
Hi, 

Does the ability exist currently (or is it in-progress) that a user could execute this scan and flag that they would like a report file generated by running something like:

check-audit --registry=https://registry.npmjs.org/ --json

i.e. in the above that a json file is physically generated?

If this didn't currently exist, could it be made available?

Thanks.

**Comment by naugtur** [comment]
Could you explain more about what you need in the output?
`npm audit --json` (the command used within) is returning all the information. I'm assuming you'd like to see the same output, but filtered to your ignores etc. ?

**Comment by rouanw** [comment]
@MarkSkillen @naugtur I've opened a pull request (https://github.com/naugtur/npm-audit-resolver/pull/10) to provide this functionality.

**Comment by MarkSkillen** [comment]
Just to clarify my original comment, I’m talking about a physical file (e.g. something like “report.json”), not just the output to the console.

**Comment by rouanw** [comment]
@MarkSkillen you can just pipe the output to a file. E.g. On *nix:

```sh
check-audit - - json > report.json
```
