### ISSUE TITLE
Make it suitable for git hooks

### ISSUE THREAD

**Issue by tothimre** [naugtur/npm-audit-resolver#9]
Hello I am using husky for mapping to git hooks easily like this

"husky": {
  "hooks": {
    "pre-commit": "npm run node_modules/.bin/resolve-audit && ...."
  }
}

If no user input possible it does not wait for the user input, that makes sense, but if there are errors it shall give back other than 0 return code, that would make this tool useful.

**Comment by naugtur** [comment]
Taht's what the check-audit command is for. I run it in CI for almost a year now.

**Comment by naugtur** [comment]
Also, instead of npm run you can use npx
https://naugtur.pl/pres3/securedev/#/18

So you use the interactive version to make decisions and the check-audit command to force yourself to :)
